#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          Logger web service
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Web interface to logger 
# Description:       Python web logger service
#                    
### END INIT INFO

LOGGER="/home/root/LOGGER/bin/web_logger"
test -f ${LOGGER} || exit 0


case "$1" in
    start)
	echo "Starting logger..."
        start-stop-daemon --start --quiet --exec sh ${LOGGER} >/dev/null 2>&1
	;;
    stop)
        echo "Stopping logger service..."
        #start-stop-daemon --stop --quiet --exec ${LOGGER}
        pgrep /usr/bin/python3 | xargs kill
	;;
    restart)
        echo "Stopping logger service..."
        pgrep /usr/bin/python3 | xargs kill
	echo "Starting logger service..."
        start-stop-daemon --start --quiet --exec sh ${LOGGER} >/dev/null 2>&1
	;;
    *)
	echo "Usage: ${LOGGER} {start|stop|restart}"
	exit 1
	;;
esac

exit 0

