version: 1

formatters:
    custom_format:
        format: "%(levelname)s - %(name)s - %(asctime)s - %(message)s"

filters:
    linear:
        name: linear

handlers:
    console:
        class: logging.StreamHandler
        formatter: custom_format
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: custom_format
        filename: '../project/Log_files/linear.log'
        filters: [linear]
        level: DEBUG
        maxBytes: 102400000
        backupCount: 5

loggers:
    linear:
        handlers: [file]
        level: DEBUG
