version: 1

formatters:
    custom_format:
        format: "%(levelname)s - %(name)s - %(asctime)s - %(message)s"

filters:
    mylogger:
        name: mylogger

handlers:
    console:
        class: logging.StreamHandler
        formatter: custom_format
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: custom_format
        filename: '../project/Log_files/mylogger.log'
        filters: [mylogger]
        maxBytes: 10240
        backupCount: 5

loggers:
    mylogger:
        handlers: [file]
        level: INFO
